---
name: "pre-release"

on:
  push:
    branches:
      - "main"
     
jobs: 
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    
    steps:
      # ...
      - name: "Builde & test"
      run: |
        echo "done!"
        
        
      -uses: "statique/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files : |
          LICENSE.txt
          *.jar
